version: "3"

services:
  workspace:
    container_name: kotlin_workspace
    build:
      context: ./docker/workspace
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    volumes:
      - .:/root/workspace
  db:
    image: postgres:latest
    container_name: kotlin_postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: postgres
